default: true
MD013:
  line_length: 120
  heading_line_length: 120
  code_block_line_length: 160
  tables: false
MD033: false  # allow inline HTML (handy for README badges)
MD041: false  # first line in file should be a top-level heading (relax)
